--------------------------------------------------------
--  文件已创建 - 星期一-九月-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAOBAO_GOODS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TAOBAO_GOODS" 
   (	"GOOD_ID" VARCHAR2(20 BYTE), 
	"GOOD_NAME" VARCHAR2(20 BYTE), 
	"GOOD_PRICE" FLOAT(126), 
	"GOOD_COUNT" NUMBER, 
	"GOOD_POINT" NUMBER, 
	"SHOP_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAOBAO_SHOP
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TAOBAO_SHOP" 
   (	"SHOP_ID" VARCHAR2(20 BYTE), 
	"SHOP_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAOBAO_CAR
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TAOBAO_CAR" 
   (	"CAR_ID" VARCHAR2(20 BYTE), 
	"GOOD_ID" VARCHAR2(20 BYTE), 
	"GOOD_COUNT" NUMBER, 
	"DELETEFLAG" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.TAOBAO_GOODS
SET DEFINE OFF;
Insert into SCOTT.TAOBAO_GOODS (GOOD_ID,GOOD_NAME,GOOD_PRICE,GOOD_COUNT,GOOD_POINT,SHOP_ID) values ('1','香奈儿唇膏3.5g',265,4,12,'1');
Insert into SCOTT.TAOBAO_GOODS (GOOD_ID,GOOD_NAME,GOOD_PRICE,GOOD_COUNT,GOOD_POINT,SHOP_ID) values ('2','蓝轻盈粉底液',85,3,3,'2');
Insert into SCOTT.TAOBAO_GOODS (GOOD_ID,GOOD_NAME,GOOD_PRICE,GOOD_COUNT,GOOD_POINT,SHOP_ID) values ('3','化妆棉',12,2,12,'3');
REM INSERTING into SCOTT.TAOBAO_SHOP
SET DEFINE OFF;
Insert into SCOTT.TAOBAO_SHOP (SHOP_ID,SHOP_NAME) values ('1','香港我的美丽日记');
Insert into SCOTT.TAOBAO_SHOP (SHOP_ID,SHOP_NAME) values ('2','实体经营');
Insert into SCOTT.TAOBAO_SHOP (SHOP_ID,SHOP_NAME) values ('3','红豆豆的小屋');
REM INSERTING into SCOTT.TAOBAO_CAR
SET DEFINE OFF;
Insert into SCOTT.TAOBAO_CAR (CAR_ID,GOOD_ID,GOOD_COUNT,DELETEFLAG) values ('1','1',2,0);
Insert into SCOTT.TAOBAO_CAR (CAR_ID,GOOD_ID,GOOD_COUNT,DELETEFLAG) values ('2','2',1,0);
Insert into SCOTT.TAOBAO_CAR (CAR_ID,GOOD_ID,GOOD_COUNT,DELETEFLAG) values ('3','3',1,0);
--------------------------------------------------------
--  DDL for Index TAOBAO_GOODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TAOBAO_GOODS_PK" ON "SCOTT"."TAOBAO_GOODS" ("GOOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAOBAO_SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TAOBAO_SHOP_PK" ON "SCOTT"."TAOBAO_SHOP" ("SHOP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAOBAO_CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TAOBAO_CAR_PK" ON "SCOTT"."TAOBAO_CAR" ("CAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOODID_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GOODID_UNIQUE" ON "SCOTT"."TAOBAO_CAR" ("GOOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TAOBAO_GOODS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TAOBAO_GOODS" MODIFY ("GOOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_GOODS" MODIFY ("GOOD_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_GOODS" MODIFY ("GOOD_PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_GOODS" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_GOODS" MODIFY ("SHOP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_GOODS" ADD CONSTRAINT "TAOBAO_GOODS_PK" PRIMARY KEY ("GOOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAOBAO_SHOP
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TAOBAO_SHOP" MODIFY ("SHOP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_SHOP" MODIFY ("SHOP_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_SHOP" ADD CONSTRAINT "TAOBAO_SHOP_PK" PRIMARY KEY ("SHOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAOBAO_CAR
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TAOBAO_CAR" ADD CONSTRAINT "GOODID_UNIQUE" UNIQUE ("GOOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."TAOBAO_CAR" MODIFY ("CAR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_CAR" MODIFY ("GOOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_CAR" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_CAR" MODIFY ("DELETEFLAG" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TAOBAO_CAR" ADD CONSTRAINT "TAOBAO_CAR_PK" PRIMARY KEY ("CAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
